Repository PyFstat/PyFstat, pull requests merged in 2021-04, with the labels that each got.

#300 codecov.yml: only run on pyfstat package dir
  .github/workflows/codecov.yml
Labels: tests

#301 codecov: ignore pyfstat/_version.py
  .github/codecov.yml
Labels: tests

#302 move codecov.yml to top directory
  codecov.yml
Labels: tests

#299 add requirements.txt and tests.py to MANIFEST.in
  MANIFEST.in
Labels: packaging

#253 JOSS paper
  README.md
  joss-paper/.gitignore
  joss-paper/Makefile
  joss-paper/arxiv/arxiv-abstract.txt
  joss-paper/arxiv/paper-arxiv-v1.tex
  joss-paper/arxiv/paper-arxiv-v2.tex
  joss-paper/build-paper-with-docker.sh
  joss-paper/joss-submission-notes.txt
  joss-paper/latex.template
  joss-paper/logo-empty.png
  joss-paper/logo.png
  joss-paper/paper.bib
  joss-paper/paper.md
Labels: documentation

#307 Simplify if-mkdir block to makedirs-exist_ok
  pyfstat/grid_based_searches.py
  pyfstat/mcmc_based_searches.py
Labels: grids, mcmc

#310 Add return statement to get_semicoherent_twoF()
  pyfstat/core.py
Labels: core, enhancement

#312 Replace requirements for extras require
  .github/workflows/codecov.yml
  .github/workflows/integration.yml
  .github/workflows/run_examples.yml
  .readthedocs.yml
  Dockerfile
  MANIFEST.in
  README.md
  bin/get-and-export-ephemeris.sh
  bin/setup-dev-tools.sh
  docs/requirements.txt
  requirements-dev.txt
  requirements.txt
  setup.py
Labels: dependencies, meta

#315 tests: cover MCMC plotting methods
  tests.py
Labels: mcmc, tests

#318 init_computefstatistic(): remove use_aPlus print statement
  pyfstat/core.py
Labels: core

#319 TestComputeFstat: cover predict_twoF_cumulative()
  tests.py
Labels: core, tests

#317 Fix cumulative plots for transients, extend examples and tests
  examples/mcmc_examples/PyFstat_example_fully_coherent_MCMC_search.py
  examples/transient_examples/PyFstat_example_long_transient_MCMC_search.py
  examples/transient_examples/PyFstat_example_make_data_for_long_transient_search.py
  examples/transient_examples/PyFstat_example_make_data_for_short_transient_search.py
  examples/transient_examples/PyFstat_example_short_transient_MCMC_search.py
  pyfstat/core.py
  pyfstat/helper_functions.py
  pyfstat/mcmc_based_searches.py
  tests.py
Labels: enhancement, examples, plotting, tests, transients

#320 TestGridSearch: basic plots coverage
  tests.py
Labels: grids, plotting, tests

#303 .zenodo.json: add readthedocs as related_identifier
  .zenodo.json
Labels: documentation, meta

#324 make black 21.4b2 happy: no extra whitespace in one-line docstrings
  examples/mcmc_vs_grid_simple_example/PyFstat_example_simple_mcmc_vs_grid_comparison.py
  pyfstat/core.py
  pyfstat/gridcorner.py
  pyfstat/mcmc_based_searches.py
Labels: documentation

#322 stop pinning numpy<1.20
  setup.py
Labels: packaging

#325 setup.py : add project_urls for PyPI sidebar
  setup.py
Labels: packaging
