Repository PyFstat/PyFstat, pull requests merged in 2021-02, with the labels that each got.

#273 pin numpy<1.20 to fix lalsuite incompatibility
  requirements.txt
  setup.py
Labels: meta, tests

#276 integration.yml: also trigger on pull_request
  .github/workflows/integration.yml
Labels: meta, tests

#274 update citation requests in README
  README.md
Labels: documentation

#279 avoid duplicate checks on internal PRs
  .github/workflows/integration.yml
Labels: meta

#278 fix and test FrequencyModulatedArtifactWriter
  CHANGELOG.md
  pyfstat/make_sfts.py
  tests.py
Labels: injections, tests

#282 remove tests from compiled docs
  docs/source/modules.rst
  docs/source/tests.rst
Labels: documentation

#281 Implement line writer
  pyfstat/__init__.py
  pyfstat/make_sfts.py
  tests.py
Labels: enhancement, injections

#283 fix conda badge in README.md
  README.md
Labels: meta

#210 add python 3.9 to integration.yml
  .github/workflows/integration.yml
Labels: meta, tests
