Repository PyFstat/PyFstat, pull requests merged in 2022-11, with the labels that each got.

#489 fix segfault in get_semicoherent_single_IFO_twoFs() with recent lalsuite
  docs/source/pyfstat.utils.rst
  pyfstat/core.py
  pyfstat/utils/__init__.py
  pyfstat/utils/atoms.py
  tests/test_utils/test_atoms.py
Labels: core

#492 Writer timestamps handling improvements
  pyfstat/make_sfts.py
  tests/test_make_sfts.py
Labels: enhancement, data

#486 485 refurbish injection parameters
  examples/other_examples/PyFstat_example_InjectionParametersGenerator.py
  examples/tutorials/1_generating_signals.ipynb
  pyfstat/injection_parameters.py
  pyfstat/make_sfts.py
  tests/test_injection_parameters.py
  tests/test_old_api_injection_parameters.py
Labels: enhancement, injections

#496 add sphinx_autodoc_defaultargs and update to sphinx 5.3.0
  docs/source/conf.py
  setup.py
Labels: documentation

#503 test_cli.py/Only actually test that INFO messages match
  tests/test_utils/test_cli.py
Labels: tests

#504 Update codecov.yml
  .github/workflows/codecov.yml
Labels: meta

#505 fix attributes bug in TransientGridSearch if no actual transient parameters are set
  pyfstat/grid_based_searches.py
  tests/test_grid_based_searches.py
Labels: bug, grids, tests, transients

#506 write_atoms_to_file: change header comments to %%
  pyfstat/core.py
  tests/test_core.py
Labels: core

#495 pin lalsuite==7.11
  etc/pyfstat-dev.yml
  setup.py
Labels: dependencies

#507 update changelog for 1.19.0
  CHANGELOG.md
Labels: documentation, releases
