Repository PyFstat/PyFstat, pull requests merged in 2022-06, with the labels that each got.

#400 init_transient_fstat_map_features: be strict about feature strings
  pyfstat/core.py
  pyfstat/tcw_fstat_map_funcs.py
Labels: transients

#399 README: clarify lalsuite-from-source
  README.md
Labels: documentation

#404 pin numpy<1.23.0 to avoid ptemcee index errors
  setup.py
Labels: dependencies

#406 Add new method to convert h0 and snr
  pyfstat/snr.py
  tests/test_snr.py
Labels: enhancement

#407 DetectorStates: fix argument name in docstring
  pyfstat/snr.py
Labels: documentation, misc-modules

#408 README: reorganise install methods
  README.md
Labels: documentation

#409 fix ptemcee incompatibility with numpy 1.23.0 via local copies of autocorr functions
  pyfstat/mcmc_based_searches.py
  setup.py
Labels: mcmc, dependencies

#410 Writer: remove deprecated timestampsFiles option
  pyfstat/make_sfts.py
Labels: data
