Repository PyFstat/PyFstat, pull requests merged in 2022-03, with the labels that each got.

#378 move injection parameter generators to new module, simplify Writer class
  pyfstat/__init__.py
  pyfstat/injection_parameters.py
  pyfstat/make_sfts.py
  setup.py
  tests.py
Labels: enhancement, meta, injections

#379 Add Python API to compute SNR
  docs/source/pyfstat.rst
  pyfstat/__init__.py
  pyfstat/snr.py
  tests.py
Labels: enhancement, injections, helper_functions

#381 Split test suite
  .github/workflows/codecov.yml
  .github/workflows/conda-test.yml
  .github/workflows/integration.yml
  .github/workflows/test_lalsuite_dev.yml
  tests/test_old_suite.py
  tests/test_snr.py
Labels: meta, tests

#384 retry MCMC quantile failures thrice via flaky
  README.md
  setup.py
  tests/test_old_suite.py
Labels: mcmc, tests

#387 Use isort for sorting import statement, more pre-commit hooks
  .pre-commit-config.yaml
  CHANGELOG.md
  README.md
  docs/source/conf.py
  examples/binary_examples/PyFstat_example_binary_mcmc_vs_grid_comparison.py
  examples/binary_examples/PyFstat_example_semi_coherent_binary_search_using_MCMC.py
  examples/followup_examples/PyFstat_example_semi_coherent_directed_follow_up.py
  examples/glitch_examples/PyFstat_example_glitch_robust_directed_MCMC_search_on_1_glitch.py
  examples/glitch_examples/PyFstat_example_glitch_robust_directed_grid_search_on_1_glitch.py
  examples/glitch_examples/PyFstat_example_make_data_for_search_on_1_glitch.py
  examples/glitch_examples/PyFstat_example_standard_directed_MCMC_search_on_1_glitch.py
  examples/grid_examples/PyFstat_example_grid_search_F0.py
  examples/grid_examples/PyFstat_example_grid_search_F0F1.py
  examples/grid_examples/PyFstat_example_grid_search_F0F1F2.py
  examples/grid_examples/PyFstat_example_grid_search_with_BSGL.py
  examples/mcmc_examples/PyFstat_example_MCMC_search_using_initialisation.py
  examples/mcmc_examples/PyFstat_example_fully_coherent_MCMC_search.py
  examples/mcmc_examples/PyFstat_example_fully_coherent_MCMC_search_with_BSGL.py
  examples/mcmc_examples/PyFstat_example_semi_coherent_MCMC_search.py
  examples/mcmc_vs_grid_simple_example/PyFstat_example_simple_mcmc_vs_grid_comparison.py
  examples/other_examples/PyFstat_example_InjectionParametersGenerator.py
  examples/other_examples/PyFstat_example_injecting_into_noise_sfts.py
  examples/other_examples/PyFstat_example_spectrogram.py
  examples/other_examples/PyFstat_example_twoF_cumulative.py
  examples/run_all_examples.py
  examples/transient_examples/PyFstat_example_long_transient_MCMC_search.py
  examples/transient_examples/PyFstat_example_make_data_for_long_transient_search.py
  examples/transient_examples/PyFstat_example_make_data_for_short_transient_search.py
  examples/transient_examples/PyFstat_example_short_transient_MCMC_search.py
  examples/transient_examples/PyFstat_example_short_transient_grid_search.py
  pyfstat/__init__.py
  pyfstat/core.py
  pyfstat/grid_based_searches.py
  pyfstat/gridcorner.py
  pyfstat/helper_functions.py
  pyfstat/injection_parameters.py
  pyfstat/make_sfts.py
  pyfstat/mcmc_based_searches.py
  pyfstat/optimal_setup_functions.py
  pyfstat/snr.py
  pyfstat/tcw_fstat_map_funcs.py
  setup.cfg
  setup.py
  tests/commons_for_tests.py
  tests/test_core.py
  tests/test_grid_based_searches.py
  tests/test_injection_parameters.py
  tests/test_make_sfts.py
  tests/test_mcmc_based_searches.py
  tests/test_snr.py
Labels: meta

#390 remove deprecated $LALPULSAR_DATADIR use for ephemerides
  Dockerfile
  README.md
  pyfstat/core.py
  pyfstat/helper_functions.py
Labels: core, packaging, helper_functions

#391 Add manal trigger to docker action
  .github/workflows/docker-publish.yml
Labels: meta
