Repository PyFstat/PyFstat, pull requests merged in 2022-10, with the labels that each got.

#459 Reformulate instructions to use lalsuite from source
  README.md
Labels: documentation

#477 add more issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: meta

#483 Writer: downgrade warning to info about noiseSFTs/tstart/duration
  pyfstat/make_sfts.py
Labels: data

#482 add wrapper for lalpulsar.OfficialSFTFilename
  pyfstat/make_sfts.py
  pyfstat/utils/__init__.py
  pyfstat/utils/sft.py
Labels: data, utils

#480 add (h0,cosi)<->(aplus,across) functions to utils.converting
  pyfstat/snr.py
  pyfstat/utils/__init__.py
  pyfstat/utils/converting.py
  tests/test_utils/test_converting.py
Labels: enhancement, utils
