Repository PyFstat/PyFstat, pull requests merged in 2022-08, with the labels that each got.

#424 pin flake8<5.0
  setup.py
Labels: tests, dependencies

#426 lalapps->lalpulsar migration with compatibility helper function
  pyfstat/grid_based_searches.py
  pyfstat/helper_functions.py
  pyfstat/make_sfts.py
  pyfstat/mcmc_based_searches.py
  pyfstat/snr.py
  tests/test_grid_based_searches.py
  tests/test_helper_functions.py
  tests/test_make_sfts.py
Labels: data, grids, mcmc, tests, misc-modules

#428 Hotfix timestamps snr
  pyfstat/snr.py
  tests/test_snr.py
Labels: bug, tests, misc-modules

#429 Miscelaneous overhaul: LaTeX, notebooks, bashplotlib, tqdm, argparse
  .pre-commit-config.yaml
  README.md
  etc/pyfstat-dev.yml
  examples/tutorials/0_generating_noise.ipynb
  examples/tutorials/1_generating_signals.ipynb
  pyfstat/core.py
  pyfstat/grid_based_searches.py
  pyfstat/helper_functions.py
  pyfstat/make_sfts.py
  pyfstat/mcmc_based_searches.py
  setup.py
Labels: core, examples, meta

#432 Deprecate old MCMCFollowUpSearch and optimal setup functions
  pyfstat/mcmc_based_searches.py
Labels: followup

#438 finish lalapps->lalpulsar migration
  etc/pyfstat-dev.yml
  pyfstat/helper_functions.py
  pyfstat/make_sfts.py
Labels: documentation, misc-modules, dependencies

#439 Revert "pin flake8<5.0"
  .pre-commit-config.yaml
  setup.py
Labels: dependencies

#440 drop python 3.7
  .github/workflows/integration.yml
  .github/workflows/test_lalsuite_dev.yml
  CHANGELOG.md
  README.md
  etc/pyfstat-dev.yml
  setup.py
Labels: tests, dependencies

#445 Refurbish logging pytestconfig
  pyfstat/__init__.py
  pytest.ini
Labels: tests

#435 Refurbish logging
  .gitignore
  docs/source/conf.py
  docs/source/pyfstat.rst
  examples/binary_examples/PyFstat_example_binary_mcmc_vs_grid_comparison.py
  examples/binary_examples/PyFstat_example_semi_coherent_binary_search_using_MCMC.py
  examples/followup_examples/PyFstat_example_semi_coherent_directed_follow_up.py
  examples/glitch_examples/PyFstat_example_glitch_robust_directed_MCMC_search_on_1_glitch.py
  examples/glitch_examples/PyFstat_example_glitch_robust_directed_grid_search_on_1_glitch.py
  examples/glitch_examples/PyFstat_example_standard_directed_MCMC_search_on_1_glitch.py
  examples/grid_examples/PyFstat_example_grid_search_F0.py
  examples/grid_examples/PyFstat_example_grid_search_F0F1.py
  examples/grid_examples/PyFstat_example_grid_search_F0F1F2.py
  examples/grid_examples/PyFstat_example_grid_search_with_BSGL.py
  examples/mcmc_examples/PyFstat_example_MCMC_search_using_initialisation.py
  examples/mcmc_examples/PyFstat_example_fully_coherent_MCMC_search.py
  examples/mcmc_examples/PyFstat_example_fully_coherent_MCMC_search_with_BSGL.py
  examples/mcmc_examples/PyFstat_example_semi_coherent_MCMC_search.py
  examples/mcmc_vs_grid_simple_example/PyFstat_example_simple_mcmc_vs_grid_comparison.py
  examples/other_examples/PyFstat_example_InjectionParametersGenerator.py
  examples/other_examples/PyFstat_example_injecting_into_noise_sfts.py
  examples/other_examples/PyFstat_example_spectrogram.py
  examples/other_examples/PyFstat_example_twoF_cumulative.py
  examples/run_all_examples.py
  examples/transient_examples/PyFstat_example_long_transient_MCMC_search.py
  examples/transient_examples/PyFstat_example_make_data_for_long_transient_search.py
  examples/transient_examples/PyFstat_example_make_data_for_short_transient_search.py
  examples/transient_examples/PyFstat_example_short_transient_MCMC_search.py
  examples/transient_examples/PyFstat_example_short_transient_grid_search.py
  examples/tutorials/0_generating_noise.ipynb
  examples/tutorials/1_generating_signals.ipynb
  pyfstat/__init__.py
  pyfstat/core.py
  pyfstat/grid_based_searches.py
  pyfstat/helper_functions.py
  pyfstat/injection_parameters.py
  pyfstat/logging.py
  pyfstat/make_sfts.py
  pyfstat/mcmc_based_searches.py
  pyfstat/optimal_setup_functions.py
  pyfstat/snr.py
  pyfstat/tcw_fstat_map_funcs.py
  pytest.ini
  setup.py
  tests/test_logging.py
Labels: core
