Repository PyFstat/PyFstat, pull requests merged in 2022-12, with the labels that each got.

#510 isotropic_amplitude_priors is not global anymore
  examples/other_examples/PyFstat_example_InjectionParametersGenerator.py
  examples/tutorials/1_generating_signals.ipynb
  pyfstat/__init__.py
  pyfstat/injection_parameters.py
Labels: bug, examples

#516 pin numpy<1.24.0
  CHANGELOG.md
  README.md
  etc/pyfstat-dev.yml
  setup.py
Labels: dependencies

#517 init_transient_fstat_map_features: upgrade cuda/device info from DEBUG to INFO
  pyfstat/tcw_fstat_map_funcs.py
Labels: enhancement, transients
